"""empty message

Revision ID: 039ed7169687
Revises: 7528aa679030
Create Date: 2021-11-05 22:32:30.560691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039ed7169687'
down_revision = '7528aa679030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Picture',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Picture_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Picture_pkey')
    )
    # ### end Alembic commands ###
