"""empty message

Revision ID: 6fc08d64131b
Revises: ad10511474be
Create Date: 2021-11-06 08:20:40.629265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc08d64131b'
down_revision = 'ad10511474be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'Image',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'Image',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
